/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cardgame;

import java.net.URL;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
/**
 *
 * @author user pc
 */
public class index extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    int count = 0;
    ArrayList<String> sampleArray = new ArrayList<>();
    ArrayList<Card> cards = new ArrayList<>();
    
    String[] suits = {"Clubs","Diamonds","Hearts","Spades"};
    String[] nonNumberCards = {"Ace","Jack","Queen","King"};
    
    Card playerCard;
    Card computerCard;
    
    String player = null;
    double amount = 100;
    
    public index() {
        initComponents();
        setLocationRelativeTo(null);
        Deck(cards);
        count = 0;
    }
    
    public index(String player, double amount) {
        initComponents();
        setLocationRelativeTo(null);
        Deck(cards);
        
        this.player = player;
        this.amount = amount;
        count = 0;
        
        DecimalFormat df = new DecimalFormat("#.##");
        String formattedAmount = df.format(amount);
        
        username.setText(player);
        cashLabel.setText(String.valueOf(formattedAmount));
    }
    
    
    public void Deck(ArrayList<Card> cards){
        for(int value = 2; value <= 10; value++)
        {   
            for(int index = 0; index < suits.length; index++)
            {
               cards.add(new Card(value + suits[index],value)); 
            }
        }
        
        for(int pos = 1; pos < nonNumberCards.length; pos++)
        {
            for(int index = 0; index < suits.length; index++)
            {
                cards.add(new Card(nonNumberCards[pos] + suits[index],pos + 10));
            }
        }
        
        for(int pos = 0; pos < 1; pos++)
        {
            for(int index = 0; index < suits.length; index++)
            {
                cards.add(new Card(nonNumberCards[pos] + suits[index],pos + 1));
            }
        }  
    }
    
    public Card play(ArrayList<Card> cards){
        Card obj = new Card();
        Collections.shuffle(cards);
        
        Random random = new Random();
        int randomIndex = random.nextInt(cards.size());
        
        obj = cards.get(randomIndex);
        cards.remove(randomIndex);
        
        return obj;
    }
    
    public void getData()
    {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnQuit = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        playerCardLabel = new javax.swing.JLabel();
        playBtn = new javax.swing.JButton();
        roundLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        computerCardLabel = new javax.swing.JLabel();
        betAmountTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        cashLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 0));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cardLogo.png"))); // NOI18N
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 88));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Card Clash");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 33, -1, -1));

        btnQuit.setBackground(new java.awt.Color(51, 51, 51));
        btnQuit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnQuit.setForeground(new java.awt.Color(255, 0, 0));
        btnQuit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Quit.png"))); // NOI18N
        btnQuit.setText("Quit");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });
        jPanel5.add(btnQuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, -1, -1));

        username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("username@gmail.com");
        jPanel5.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 80, 110, -1));

        jPanel2.setBackground(new java.awt.Color(204, 255, 0));

        playerCardLabel.setBackground(new java.awt.Color(255, 255, 255));
        playerCardLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerCardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backCard.jpg"))); // NOI18N

        playBtn.setBackground(new java.awt.Color(255, 255, 204));
        playBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        playBtn.setText("PLAY");
        playBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBtnActionPerformed(evt);
            }
        });

        roundLabel.setBackground(new java.awt.Color(255, 255, 255));
        roundLabel.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        roundLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roundLabel.setText("0 of 26");

        jLabel8.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rounds.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PlayerIcon.png"))); // NOI18N
        jLabel6.setText("Player");

        jLabel4.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ComputerIcon.png"))); // NOI18N
        jLabel4.setText("Computer");

        computerCardLabel.setBackground(new java.awt.Color(255, 255, 255));
        computerCardLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        computerCardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backCard.jpg"))); // NOI18N

        betAmountTxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        betAmountTxt.setForeground(new java.awt.Color(0, 102, 153));
        betAmountTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        betAmountTxt.setToolTipText("Bet Amount");
        betAmountTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Dollar.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(playerCardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(roundLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(playBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(betAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(computerCardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(85, 85, 85))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roundLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(betAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(playBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(computerCardLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                    .addComponent(playerCardLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 51));

        cashLabel.setFont(new java.awt.Font("Imprint MT Shadow", 3, 30)); // NOI18N
        cashLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cashLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cash.png"))); // NOI18N
        cashLabel.setText("10,000");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cashLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cashLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playBtnActionPerformed
        
        
        if (cards.isEmpty()) {
            Connection connection;
            ResultSet resultSet;
            Statement statement;
            PreparedStatement preparedStatement;
            
            try
            {
                 Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                 connection = DriverManager.getConnection("jdbc:ucanaccess://Database.accdb");
                 String sql = "UPDATE player SET amount = '"+amount+"'";
                 statement = connection.createStatement();
                
                 statement.executeUpdate(sql);
                 
                 //JOptionPane.showMessageDialog(null, "ACCOUNT CREATED!!!\nThank you for creating an account you have beeen awarded\nR10,000 to play with!!!");
                 JOptionPane.showMessageDialog(null, "GAME OVER\nTHANK YOU FOR PLAYING!");
                 new login().setVisible(true);
                 this.dispose();
            }
            catch(Exception ex)
            {
               JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
        else
        {
           playerCard = play(cards);
            computerCard = play(cards); 
        }

        
       if(betAmountTxt.getText().isEmpty())
       {
           JOptionPane.showMessageDialog(null,"Please Enter Bet Amount Before Playing!");
       }
       else if(Double.parseDouble(betAmountTxt.getText()) > 100 || Double.parseDouble(betAmountTxt.getText()) < 10)
       {
           JOptionPane.showMessageDialog(null,"Invalid Bet Amount\nMinimum:10\nMaximum:100");
       }
       else if(amount < 10)
       {
           JOptionPane.showMessageDialog(null, "You Amount Is Below Minimum Bet Place");
       }
       else if(count > 25)
       {
           count--;
           JOptionPane.showMessageDialog(null, "GAME OVER\nTHANK YOU FOR PLAYING");
       }
       else
       {
           double betAmount = Double.parseDouble(betAmountTxt.getText());
           
            ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
            URL imageURL = classLoader.getResource("images/" + playerCard.getCardName()+ ".png");
            URL imageURL2 = classLoader.getResource("images/" + computerCard.getCardName() + ".png");
                  
            if(imageURL != null) {
                ImageIcon cardImage1 = new ImageIcon(imageURL);
                playerCardLabel.setIcon(cardImage1);

                ImageIcon cardImage2 = new ImageIcon(imageURL2);
                computerCardLabel.setIcon(cardImage2);

                ++count;
                roundLabel.setText(count+" of 26");
                
                if(playerCard.getCardValue() > computerCard.getCardValue())
                {
                    amount += betAmount;
                }
                else if(playerCard.getCardValue() < computerCard.getCardValue())
                {
                    amount -= betAmount;
                }
                else
                {
                    amount = amount;
                }
                
                DecimalFormat df = new DecimalFormat("#.##");
                String formattedAmount = df.format(amount);
                cashLabel.setText(String.valueOf(formattedAmount));
                System.out.println("Image loaded successfully.");
            } else {
                System.err.println("Image loading failed.");
            }
       }
        
    }//GEN-LAST:event_playBtnActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit the game?", "Confirmation", JOptionPane.YES_NO_OPTION);

        if (dialogResult == JOptionPane.YES_OPTION) 
        {
            Connection connection;
            ResultSet resultSet;
            Statement statement;
            PreparedStatement preparedStatement;
            
            try
            {
                 Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                 connection = DriverManager.getConnection("jdbc:ucanaccess://Database.accdb");
                 String sql = "UPDATE player SET amount = '"+amount+"'";
                 statement = connection.createStatement();
                
                 statement.executeUpdate(sql);
                 
                 //JOptionPane.showMessageDialog(null, "ACCOUNT CREATED!!!\nThank you for creating an account you have beeen awarded\nR10,000 to play with!!!");
                 new login().setVisible(true);
                 this.dispose();
            }
            catch(Exception ex)
            {
               JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        } 
        else 
        {
            System.out.println("User clicked 'No' or closed the dialog. Action canceled.");
        }
    }//GEN-LAST:event_btnQuitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField betAmountTxt;
    private javax.swing.JButton btnQuit;
    private javax.swing.JLabel cashLabel;
    private javax.swing.JLabel computerCardLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton playBtn;
    private javax.swing.JLabel playerCardLabel;
    private javax.swing.JLabel roundLabel;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
